# Generated by Django 3.1.4 on 2021-06-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210623_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(default='', verbose_name='Ссылка на пользователя'),
        ),
    ]
