# Generated by Django 3.1.4 on 2021-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ссылка на пользователя'),
        ),
    ]
