# Generated by Django 3.1.4 on 2021-06-23 11:24

import ckeditor.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=main.models.generate_filename, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
