# Generated by Django 3.1.4 on 2021-06-23 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210623_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
