# Generated by Django 3.1.4 on 2021-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210624_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_status',
            field=models.BooleanField(default=False, verbose_name='Статус публикации'),
        ),
    ]
